version: '3.2'
services:
  
  airflow-db:
    image: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow-demo
      POSTGRES_DB: postgres
    networks:
      - dbnet
    ports:
      - "35432:5432"

networks:
  dbnet:
    driver: bridge
